spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8
    username: root
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
    timeout: 0
#  profiles:
#    active: dev
  profiles:
      active:
        - dubbo
  dubbo:
      base-package: com.yp.consumerserver
      application:
        name: yp-consumer
        consumer:                    # 公用的消费者配置
           lazy: true
           timeout: 1000
        organization:
      protocol:
        port: 20881  # 可选 性能调优 远程服务调用超时时间(毫秒) 1.0.16以上版本


